# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-30 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MyPaymentApp.Base')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('amount', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=250)),
            ],
            bases=('MyPaymentApp.base',),
        ),
        migrations.CreateModel(
            name='RazorpayResponsew',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MyPaymentApp.Base')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('response', models.TextField()),
                ('status', models.CharField(choices=[(2, b'Success'), (1, b'Pending'), (0, b'Failed')], max_length=2)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyPaymentApp.PaymentDetails')),
            ],
            bases=('MyPaymentApp.base',),
        ),
    ]
