# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyPaymentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MyPaymentApp.Base')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('PayType', models.CharField(choices=[(2, b'Full Payment'), (1, b'Partial Sattlement'), (0, b'Advance Pay')], max_length=2)),
                ('amount', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=250)),
            ],
            bases=('MyPaymentApp.base',),
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='base_ptr',
        ),
        migrations.AlterField(
            model_name='razorpayresponsew',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyPaymentApp.PaymentDetail'),
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
