# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPaymentApp', '0003_auto_20191230_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='PayType',
            field=models.IntegerField(choices=[(2, b'Full_Payment'), (1, b'Partial_Sattlement'), (0, b'Advance_Pay')], default=b'Full_Payment'),
        ),
    ]
